baseURL = "https://idx01.whistler.page"
title = "idx01 Catalog"
author = "wistlyr"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "vnovel"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "G-1234567890"

# Disqus Comment System
#disqusShortname = ""

[params]
# The number of articles to be displayed on a single page.
paginator_pages = "6"

# Site logo.
#logo = ""

  [params.homepage_meta_tags]
    meta_description = "Systemware® intranet server for Watercolor builds."
    meta_og_title = "idx01 Catalog"
    meta_og_type = "website"
    meta_og_url = "https://idx01.whistler.page"
    meta_og_image = "https://idx01.whistler.page/img/setup.png"
    meta_og_description = "Systemware® intranet server for Watercolor builds."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "https://idx01.whistler.page"
    meta_twitter_creator = "@wistlyr"


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "https://watercolor.whistler.page"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

# If you're using Yandex.Metrica, you can enable this feature.
#[params.analytics.yandexmetrica]
#    enabled = true
#    tagNumber = ''
